# Google Cloud Build Configuration for Loist Music Library MCP Server
# Optimized production deployment: Build → Push → Deploy

steps:
  # Step 1: Build Docker image with optimized caching
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build',
      # Target runtime stage (Alpine-based, more reliable than distroless)
      '--target', 'runtime',
      # Enable BuildKit for better performance and caching
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      # Use cache from previous builds
      '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:latest',
      # Enable BuildKit cache mounts for faster builds
      '--build-arg', 'BUILDKIT_PROGRESS=plain',
      # Optimized tagging: commit SHA and latest only
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:${_COMMIT_SHA}',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:latest',
      # Build context
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'
    timeout: '600s'

  # Step 2: Push Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp']
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run (uses built-in health checks)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'music-library-mcp'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:${_COMMIT_SHA}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=600s'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--port=8080'
      # Explicit command override to ensure correct startup (fallback if Dockerfile CMD is misinterpreted)
      - '--command=/usr/local/bin/python'
      - '--args=/app/src/server.py'
      - '--set-env-vars=SERVER_TRANSPORT=http,LOG_LEVEL=INFO,AUTH_ENABLED=false,ENABLE_CORS=true,CORS_ORIGINS=*,ENABLE_HEALTHCHECK=true'
      - '--set-env-vars=PORT=8080'
      - '--set-env-vars=GCS_PROJECT_ID=$PROJECT_ID'
      - '--set-env-vars=SERVER_NAME=Music Library MCP,SERVER_VERSION=0.1.0'
      - '--set-env-vars=LOG_FORMAT=text,MCP_PROTOCOL_VERSION=2024-11-05,INCLUDE_FASTMCP_META=true'
      - '--set-env-vars=ON_DUPLICATE_TOOLS=error,ON_DUPLICATE_RESOURCES=warn,ON_DUPLICATE_PROMPTS=replace'
      - '--set-env-vars=MAX_WORKERS=4,REQUEST_TIMEOUT=30,STORAGE_PATH=/tmp/storage,MAX_FILE_SIZE=104857600'
      - '--set-env-vars=GCS_REGION=us-central1,GCS_SIGNED_URL_EXPIRATION=900'
      - '--set-env-vars=DB_PORT=5432,DB_MIN_CONNECTIONS=2,DB_MAX_CONNECTIONS=10,DB_COMMAND_TIMEOUT=30'
      - '--set-env-vars=CORS_ALLOW_CREDENTIALS=true,CORS_ALLOW_METHODS=GET,POST,OPTIONS'
      - '--set-env-vars=CORS_ALLOW_HEADERS=Authorization,Content-Type,Range,X-Requested-With,Accept,Origin'
      - '--set-env-vars=CORS_EXPOSE_HEADERS=Content-Range,Accept-Ranges,Content-Length,Content-Type'
      - '--set-env-vars=EMBED_BASE_URL=https://loist.io,ENABLE_METRICS=false'
      - '--set-env-vars=DB_NAME=loist_mvp,DB_USER=music_library_user'
      - '--update-secrets=DB_CONNECTION_NAME=${_DB_CONNECTION_NAME}:latest'
      - '--update-secrets=DB_PASSWORD=${_DB_PASSWORD}:latest'
      - '--update-secrets=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}:latest'
      - '--update-secrets=BEARER_TOKEN=${_BEARER_TOKEN}:latest'
      - '--quiet'
    waitFor: ['push-image']

# Automatically tag and push images
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:${_COMMIT_SHA}'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/music-library-repo/music-library-mcp:latest'

# Build options and configuration
options:
  machineType: 'E2_HIGHCPU_8'  # Faster builds, same cost as default
  logging: CLOUD_LOGGING_ONLY

# Substitution variables (can be overridden in triggers)
substitutions:
  _COMMIT_SHA: 'local-test'
  _DB_CONNECTION_NAME: 'db-connection-name'
  _DB_PASSWORD: 'db-password'
  _GCS_BUCKET_NAME: 'gcs-bucket-name'
  _BEARER_TOKEN: 'mcp-bearer-token'

# Build timeout (reduced from 20 to 10 minutes - builds complete in ~5min)
timeout: '600s'  # 10 minutes

# Tags for organizing builds
tags:
  - 'music-library-mcp'
  - 'cloud-run'
  - 'production'
