"""
Database module for Loist Music Library MCP Server.

Provides connection pooling, query utilities, and database management
for PostgreSQL interactions.
"""

from .pool import (
    DatabasePool,
    get_connection_pool,
    get_connection,
    close_pool,
)
from .operations import (
    save_audio_metadata,
    save_audio_metadata_batch,
    get_audio_metadata_by_id,
    get_audio_metadata_by_ids,
    get_all_audio_metadata,
    search_audio_tracks,
    search_audio_tracks_advanced,
    filter_audio_tracks_xmp,
    filter_audio_tracks_combined,
    get_xmp_field_facets,
    filter_audio_tracks_cursor_xmp,
    encode_cursor,
    decode_cursor,
    update_processing_status,
    update_processing_status_batch,
    mark_as_failed,
    mark_as_completed,
    mark_as_processing,
    delete_audio_track,
    update_audio_metadata,
    # Song Publishing Operations
    create_party,
    get_party_by_id,
    search_parties,
    create_work,
    get_work_by_id,
    search_works,
    replace_work_writers,
    replace_work_publishers,
    calculate_split_warnings,
    link_artist_to_recording,
    unlink_artist_from_recording,
    # Album Operations
    create_album,
    get_album_by_id,
    update_album,
    delete_album,
    search_albums,
    add_track_to_album,
    remove_track_from_album,
    reorder_album_tracks,
    # Playlist Operations
    create_playlist,
    get_playlist_by_id,
    update_playlist,
    delete_playlist,
    search_playlists,
    add_track_to_playlist,
    remove_track_from_playlist,
    reorder_playlist_tracks,
    add_playlist_collaborator,
    remove_playlist_collaborator,
    # Upload Operations
    create_upload,
    get_upload_by_id,
    update_upload_status,
)
from .utils import check_database_availability

__all__ = [
    "DatabasePool",
    "get_connection_pool",
    "get_connection",
    "close_pool",
    "save_audio_metadata",
    "save_audio_metadata_batch",
    "get_audio_metadata_by_id",
    "get_audio_metadata_by_ids",
    "get_all_audio_metadata",
    "search_audio_tracks",
    "search_audio_tracks_advanced",
    "filter_audio_tracks_xmp",
    "filter_audio_tracks_combined",
    "get_xmp_field_facets",
    "filter_audio_tracks_cursor_xmp",
    "encode_cursor",
    "decode_cursor",
    "update_processing_status",
    "update_processing_status_batch",
    "mark_as_failed",
    "mark_as_completed",
    "mark_as_processing",
    "delete_audio_track",
    "update_audio_metadata",
    # Song Publishing Operations
    "create_party",
    "get_party_by_id",
    "search_parties",
    "create_work",
    "get_work_by_id",
    "search_works",
    "replace_work_writers",
    "replace_work_publishers",
    "calculate_split_warnings",
    "link_artist_to_recording",
    "unlink_artist_from_recording",
    # Album Operations
    "create_album",
    "get_album_by_id",
    "update_album",
    "delete_album",
    "search_albums",
    "add_track_to_album",
    "remove_track_from_album",
    "reorder_album_tracks",
    # Playlist Operations
    "create_playlist",
    "get_playlist_by_id",
    "update_playlist",
    "delete_playlist",
    "search_playlists",
    "add_track_to_playlist",
    "remove_track_from_playlist",
    "reorder_playlist_tracks",
    "add_playlist_collaborator",
    "remove_playlist_collaborator",
    # Upload Operations
    "create_upload",
    "get_upload_by_id",
    "update_upload_status",
]

